### ISSUE TITLE
Uniform Fiscal Object

### ISSUE THREAD

**Issue by x0n4r** [treygriffith/swap-compatibility#11]
Hi Support
Can you please add UFO (Uniform Fiscal Object) into the swap-compatibility list? ( https://swapready.net )
UFO is alligned as BTC 0.16.1 codebase.

Regards

https://ufobject.com
xonar

**Comment by agaddy32** [comment]
We are implemented in blocknet as well. https://twitter.com/the_blocknet/status/1017916174493986816

**Comment by treygriffith** [comment]
@x0n4r can you open a PR with the appropriate changes? see #10

**Comment by treygriffith** [comment]
The current market cap is too low to include. Closing for now.
