### ISSUE TITLE
Include Bitcoin Atom

### ISSUE THREAD

**Issue by ceeray** [treygriffith/swap-compatibility#4]
they're working on atomic swaps

**Comment by treygriffith** [comment]
Thanks @ceeray. Can you provide:
- Supported hash functions (Bitcoin derivatives typically include `RIPEMD160`, `SHA1`, and `SHA256`) and a link to the code that supports them
- Transaction malleability fix status (e.g. is SegWit on mainnet) and supporting evidence
- Support for Hashed Time Locked Contracts (typically by supporting `OP_CHECKLOCKTIMEVERIFY`, introduced in BIP65) and a link to supporting code
- Link to the software implementation that shows Bitcoin Atom in an atomic swap and its current status

**Comment by rootSig** [comment]
Hi @treygriffith 

Please see the info below:

**Supported hash functions (Bitcoin derivatives typically include RIPEMD160, SHA1, and SHA256) and a link to the code that supports them**

Bitcoin Atom (BCA) supports RIPEMD160, SHA1, SHA256 and SHA512.

Link to the code: https://github.com/bitcoin-atom/bitcoin-atom/tree/f4c9ccbcd457c64a0cefa6d54a81a540b95e51a9/src/crypto

**Transaction malleability fix status (e.g. is SegWit on mainnet) and supporting evidence**

Bitcoin Atom has SegWit working on mainnet, for instance please see
https://github.com/bitcoin-atom/bitcoin-atom/commit/2a03b2429ea7dabb3476f0cf1a4139ac24581ba6

More implementation details are on the official BCA GitHub: https://github.com/bitcoin-atom

**Support for Hashed Time Locked Contracts (typically by supporting OP_CHECKLOCKTIMEVERIFY, introduced in BIP65) and a link to supporting code**

Please see here: https://github.com/bitcoin-atom/bitcoin-atom/blob/98edcd1cd1d81c6e600574d95089b847deaa034d/src/rpc/util.cpp

For instance:
CScript CreateAtomicSwapRedeemscript(CKeyID initiator, CKeyID redeemer, int64_t locktime, int64_t secretSize, std::vector<unsigned char> secretHash)

**Link to the software implementation that shows Bitcoin Atom in an atomic swap and its current status**

Implementation of atomic swaps at BCA: https://github.com/bitcoin-atom/bitcoin-atom/blob/master/src/rpc/swap.cpp

Sample swap transactions on testnet: 
https://testnet.blockexplorer.com/tx/17888ec485a8b3aa9b9f3e13b9468a7a679373c090bac88b9ee88e1036d3cfe8
https://testnet.bitcoinatom.io/tx/3de98cbc8f5167406915a1d872a159857527da77df8d0ec61e93204d8beb3e64

Current status: BCA supports atomic swaps with most currencies listed on SwapReady including BTC, LTC, ETH, etc. on both testnet and mainnet.

**Comment by treygriffith** [comment]
@rootSig great! can you open a PR with these changes?

**Comment by treygriffith** [comment]
Thanks for submitting this. I won't include for now as the market cap is too low and the chart is pretty crowded.
