### ISSUE TITLE
Include Minexcoin

### ISSUE THREAD

**Issue by minexworker** [treygriffith/swap-compatibility#8]
Hi.
Could you include Minexcoin to the chart? It has already developed Atomic Swap implementation.
Repo is here: https://github.com/minexcoin

**Comment by treygriffith** [comment]
@minexworker can you include data for inclusion like this: https://github.com/treygriffith/swap-compatibility/issues/4

And when you do, open a PR with appropriate changes (like #10)

**Comment by treygriffith** [comment]
I'm closing as the current market cap is too low.
