### ISSUE TITLE
 Include Fujicoin

### ISSUE THREAD

**Issue by fujicoin** [treygriffith/swap-compatibility#9]
Fujicoin completed the activation of SegWit.
The implementation status of BIP is the same as Bitcoin v. 0.15.1.
https://github.com/fujicoin/fujicoin/blob/master/src/chainparams.cpp

Therefore it is compatible with Atomic Swap of On-chain and Payment Channel Network.
Please add Fujicoin to the table.
http://www.fujicoin.org/

**Comment by treygriffith** [comment]
I'm closing, as the current market cap is too low to include.
